apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  env: green
spec:
  replicas: 2 # Number of instances (pods) to run
  selector:
    matchLabels:
      app: my-container
      env: green
# everything under template is the definition of the pod that will be created.
  template:
    metadata:
      labels:
        app: my-container
        env: green
    spec:
      containers:
      - name: web-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80

        