apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2 # Number of instances (pods) to run
  selector:
    matchLabels:
      app: my-container
      env: blue
# everything under template is the definition of the pod that will be created.
  template:
    metadata:
      labels:
        app: my-container
        env: blue
    spec:
      containers:
      - name: web-app
        image: us-east1-docker.pkg.dev/assignmentweek1/testrepo/blueimage:latest
        ports:
        - containerPort: 80