name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access
    - uses: actions/checkout@v4

    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets. DOCKER_USERNAME }}
        password: ${{ secrets. DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t moscuuu/cicd:latest .
        docker push moscuuu/cicd:latest
